language: android

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb devices
  - adb shell input keyevent 82 &

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - addon

    - sys-img-armeabi-v7a-android-27

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

notifications:
  email: false
